import type { Metadata } from "next";
import "./globals.css";
import { Button } from "@/components/ui/button";
import NavLink from "@/components/NavLink";

export const metadata: Metadata = {
  title: "MoneySave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* NAVIGATION */}
        <nav className="w-full border-b">
          <div className="mx-auto max-w-6xl flex items-center justify-between  h-16">
            <h1 className="font-bold text-2xl">MoneySave</h1>

            <div className="flex items-center space-x-12">
              <NavLink />

              <Button size="sm">Get Start</Button>
            </div>
          </div>
        </nav>

        {/* PAGE CONTENT */}
        <main className="min-h-screen mx-auto max-w-6xl my-4">{children}</main>

        {/* FOOTER */}
        <footer className="w-full border-t py-4">
          <div className="mx-auto max-w-6xl px-4">
            <p className="text-sm text-gray-500">
              © 2026 Money Save. All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
